[server]
user_name = "admin"
password = "admin"
url = "http://120.79.221.36:10093"
#url = "https://api-workerd-prod.container1.titannet.io"
#url = "https://api-workerd.titannet.io"

[node]
id = "e_85a7e089-0ce4-4337-94ca-763587a07f45"

[socks5]
listenAddress = "127.0.0.1:1080"

[http]
listenAddress = "127.0.0.1:1081"

# Receive execution commands
[local_http_server]
listenAddress = "127.0.0.1:1082"

[tun]
count = 1
cap = 100

[Log]
# debug or info
level = "debug"